// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFilePicker() {
  return window['go']['main']['PickTargetService']['OpenFilePicker']();
}

export function QuickFind() {
  return window['go']['main']['PickTargetService']['QuickFind']();
}
