// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFilePicker():Promise<main.FileValidationResult>;

export function QuickFind():Promise<main.FileValidationResult>;
